name: Test Frontend

on:
  push:
    branches: 
      - main
      - setup
      - 'feature/*'
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: |
          cd frontend 
          echo "Installing dependencies"
          pnpm install 

      - name: Run lint test 
        run: |
          cd frontend
          echo "Running lint test"
          pnpm run lint

      - name: Run build test
        run: |
          cd frontend 
          echo "Running build test"
          pnpm run test-build
